"""Added referrals

Revision ID: 6a39c9165570
Revises: d3a405f03a04
Create Date: 2020-02-09 11:00:26.997823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a39c9165570'
down_revision = 'd3a405f03a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num_referrals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_referral_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral'))
    )
    op.create_index('referral_index', 'referral', ['id'], unique=True, mysql_length=255)
    op.add_column('user', sa.Column('referral', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referral')
    op.drop_index('referral_index', table_name='referral')
    op.drop_table('referral')
    # ### end Alembic commands ###
