"""Adding referral foreign key

Revision ID: 8355ab728b72
Revises: 6a39c9165570
Create Date: 2020-02-10 09:46:24.844058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8355ab728b72'
down_revision = '6a39c9165570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_user_referral_referral'), 'user', 'referral', ['referral'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_referral_referral'), 'user', type_='foreignkey')
    # ### end Alembic commands ###
