"""Adding balance and total_references to user

Revision ID: a9078a30a48e
Revises: 8355ab728b72
Create Date: 2020-02-10 11:41:28.821496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9078a30a48e'
down_revision = '8355ab728b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('total_referrals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_referrals')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###
