"""Defaulted referral counts and balance to 0

Revision ID: c49497479fe7
Revises: a9078a30a48e
Create Date: 2020-02-10 11:56:00.079749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49497479fe7'
down_revision = 'a9078a30a48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
